root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/server ./cmd/server"
bin = "./tmp/server"
delay = 1000
exclude_dir = ["tmp", "vendor", "migrations"]
include_ext = ["go"]
kill_delay = "0s"
